apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-scraper.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/component: scheduler
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: scheduler