{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "finance-scraper.fullname" . }}
  labels:
    {{- include "finance-scraper.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "finance-scraper.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }} 